// 9개
const mockData = [
  {
    detail_hash: "HBBCC",
    image: "http://public.codesquad.kr/jk/storeapp/data/fdb0d5fcfb86e332505785225a6d9ade.jpg",
    alt: "[마샐미디쉬] 유자소스 연근무침 250g",
    delivery_type: ["새벽배송", "전국택배"],
    title: "[마샐미디쉬] 유자소스 연근무침 250g",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "H1939",
    image: "http://public.codesquad.kr/jk/storeapp/data/e5646e5fc09a01a9243979b229e0572b.jpg",
    alt: "[동네부엌] 쇠고기야채장조림 200g",
    delivery_type: ["새벽배송", "전국택배"],
    title: "[동네부엌] 쇠고기야채장조림 200g",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "H8EA5",
    image: "http://public.codesquad.kr/jk/storeapp/data/4cfd1954861ebd18b5b53e558a8e902e.jpg",
    alt: "[소중한식사] 도라지초무침 150g",
    delivery_type: ["새벽배송", "전국택배"],
    title: "[소중한식사] 도라지초무침 150g",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "H602F",
    image: "http://public.codesquad.kr/jk/storeapp/data/422befe07f7e2860b9a83a8d7049ec2e.jpg",
    alt: "[미노리키친] 일본식 우엉조림(킨피라고보) 80g",
    delivery_type: ["새벽배송", "전국택배"],
    title: "[미노리키친] 일본식 우엉조림(킨피라고보) 80g",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "H9F0B",
    image: "http://public.codesquad.kr/jk/storeapp/data/d0b5d2be962947d9534e2140d1b34b2d.jpg",
    alt: "[빅마마의밥친구] 갈치포무침 150g",
    delivery_type: ["새벽배송", "전국택배"],
    title: "[빅마마의밥친구] 갈치포무침 150g",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "H0FC6",
    image: "http://public.codesquad.kr/jk/storeapp/data/f6817349118d4c671da8dca9065649a9.jpg",
    alt: "[마더앤찬] 명란치즈계란말이 230g",
    delivery_type: ["새벽배송", "전국택배"],
    title: "[마더앤찬] 명란치즈계란말이 230g",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "HCCFE",
    image: "http://public.codesquad.kr/jk/storeapp/data/757878b14ee5a8d5af905c154fc38f01.jpg",
    alt: "[옹가솜씨] 달걀곤약조림 330g",
    delivery_type: ["새벽배송", "전국택배"],
    title: "[옹가솜씨] 달걀곤약조림 330g",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "HB9C1",
    image: "http://public.codesquad.kr/jk/storeapp/data/043cf496f07899e7515f761e29d1ffa9.jpg",
    alt: "[너의반찬] 미소된장 고추무침 200g",
    delivery_type: ["새벽배송", "전국택배"],
    title: "[너의반찬] 미소된장 고추무침 200g",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "SKDNFS",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Banchan_2.jpg/330px-Banchan_2.jpg",
    alt: "위키백과 반찬",
    delivery_type: ["새벽배송", "전국택배"],
    title: "위키백과 반찬",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
];

// 6개
const temp = [
  {
    detail_hash: "235DSN",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/0606_hanjeongsik_damyang.jpg/361px-0606_hanjeongsik_damyang.jpg",
    alt: "전라도 반찬",
    delivery_type: ["새벽배송", "전국택배"],
    title: "전라도 반찬",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "11111",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Korean_cuisine-Banchan-11.jpg",
    alt: "이것은 111111",
    delivery_type: ["새벽배송", "전국택배"],
    title: "이것은 111111",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "22222",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Banchan_2.jpg/1280px-Banchan_2.jpg",
    alt: "이것은 22222",
    delivery_type: ["새벽배송", "전국택배"],
    title: "이것은 22222",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "33333",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Korean_cuisine-Ojingeochae_bokkeum-01.jpg",
    alt: "이것은 33333",
    delivery_type: ["새벽배송", "전국택배"],
    title: "이것은 33333",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "44444",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/1005_eggjjim.jpg",
    alt: "이것은 44444",
    delivery_type: ["새벽배송", "전국택배"],
    title: "이것은 44444",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
  {
    detail_hash: "55555",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Korean_pancake-Samsaek_jeon-01.jpg",
    alt: "이것은 55555",
    delivery_type: ["새벽배송", "전국택배"],
    title: "이것은 55555",
    description: "이것은 테스트용입니다.",
    s_price: "1000원",
  },
];

export default mockData;
