# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideDish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Toaster'

pod 'Alamofire', '~> 5.2'

pod 'Kingfisher', '~> 6.0'

  # Pods for SideDish

  target 'SideDishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SideDishUITests' do
    # Pods for testing
  end

end
