/*INSERT INTO SIDEDISH_CATEGORY (CATEGORY_NAME) VALUES ("main");
INSERT INTO SIDEDISH_CATEGORY (CATEGORY_NAME) VALUES ("soup");
INSERT INTO SIDEDISH_CATEGORY (CATEGORY_NAME) VALUES ("side");*/
use sidedish;
