use sidedish;

drop table if exists SIDEDISH_CATEGORY;

CREATE TABLE SIDEDISH_CATEGORY
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE SIDEDISH_ITEM
(
    ID                    BIGINT PRIMARY KEY AUTO_INCREMENT,
    ITEM_NAME             VARCHAR(100) NOT NULL UNIQUE,
    ITEM_DESCRIPTION      VARCHAR(300) NOT NULL,
    ITEM_DELIVERY_INFO    VARCHAR(200) NOT NULL,
    ITEM_DELIVERY_FEE     VARCHAR(200) NOT NULL,
    ITEM_QUANTITY         INT          NOT NULL,
    ITEM_POINT_RATE       INT          NOT NULL,
    ITEM_NORMAL_PRICE     INT          NOT NULL,
    ITEM_SALE_PRICE       INT,
    SIDEDISH_CATEGORY     BIGINT REFERENCES SIDEDISH_CATEGORY (ID),
    SIDEDISH_CATEGORY_KEY INT
);
